### ISSUE TITLE
Clarification required for Full Stack Dev Challenge

### ISSUE THREAD

**Issue by digitalfu** [skinanalytics/technical-tests#1]
Would you like the Full Stack Challenge to be completed with or without frameworks.

For a 3 hour challenge I would use frameworks and code generators to minimize boiler plate effort, but as you have mentioned they come and go it is unclear if you want that.

Can you please clarify?

**Comment by tseropian** [comment]
This is completely up to you, but considering what you already know about our tech stack during the first interview, the job desc, and the timeframe, you should be able to make up your choice.
